name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: chromium-latest

    strategy:
      matrix:
        browser: [chromium,]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --browser=${{ matrix.browser }}

    - name: Upload Playwright test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
